name: Unit Tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-20.04]

        cc: [clang]
        exclude:
          - os: windows-latest
            cc: clang

        include:
          - os: ubuntu-20.04
            cc: gcc
          - os: ubuntu-20.04
            cc: tcc
          - os: windows-latest
            cc: cl

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Ninja (Ubuntu)
      if: contains(matrix.os, 'ubuntu')
          # sudo apt-get update -y && 
      run: sudo apt-get install -y ninja-build

    - name: Install Ninja (macOS)
      if: contains(matrix.os, 'macos')
      run: brew install ninja

    - name: Install TinyCC (Ubuntu+tcc)
      if: contains(matrix.cc, 'tcc')
      run: sudo apt-get install -y tcc

    - name: Run ci-unix (Ubuntu, macOS)
      if: ${{ !contains(matrix.os, 'windows') }}
      run: test/tools/ci-unix.sh
      env:
        CC: ${{ matrix.cc }}

    - name: Run ci-windows (Windows)
      if: contains(matrix.os, 'windows')
      shell: cmd
      run: test\\tools\\ci-windows.bat
